name: test-action
on:
  push:
    branches: [ main ]
  
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello message in testing
        run: echo "Hello, world! from testing job"
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
      - name: Run hello message in deploy
        run: echo "Hello, world! from deploy job"
    
